Models/Wedding.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace WeddingPlanner.Models
{
    public class Wedding
    {
        [Key]
        public int WeddingId {get; set;}

        [Required]
        public string Bride {get; set;}

        [Required]
        public string Groom {get; set;}

        [Required(ErrorMessage="You must have a wedding date?!")]
        [DataType(DataType.Date)]
        public DateTime Date {get; set;}

        [Required]
        public string Address {get; set;}

        public DateTime CreatedAt {get; set;} = DateTime.Now;

        public DateTime UpdatedAt {get; set;} = DateTime.Now;

        public int UserId {get; set;}
        public MainUser WeddingCreator {get; set;}

        public List<Attending> Attendees { get; set; }

    }
}

Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WeddingPlanner.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace WeddingPlanner.Controllers
{
    [Route("wedding")]
    public class WeddingController : Controller
    {
        public MainUser ActiveUser
        //produces ActiveUser object that matches that of SessionUser
        {
            get { return dbContext.Users.FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("user_Id")); }
        }

        private MyContext dbContext;
        public WeddingController(MyContext context)
        {
            dbContext = context;
        }

        [HttpGet("dashboard")]
        public IActionResult Index()
        {
            if(ActiveUser == null)
            {
                return RedirectToAction("Register", "Home");
            }

            ViewBag.User = ActiveUser;
            ViewBag.Weddings = dbContext.Weddings
            .Include(w => w.Attendees)
            .ThenInclude(a => a.attendingGuests);
            // .OrderByDescending(w => w.CreatedAt);
            return View("Index");
        }

        [HttpGet("{weddingId}")]
        public IActionResult WeddingInfo(int weddingId)
        {
            if(ActiveUser == null)
            {
                return RedirectToAction("Register", "Home");
            }

            var wedding_Info = dbContext.Weddings
            .Include(w => w.Attendees)
            .ThenInclude(a => a.attendingGuests)
            .FirstOrDefault(a => a.WeddingId == weddingId);
            ViewBag.Wedding = wedding_Info;
            return View();
        }

        [HttpGet("new_wedding")]
        public IActionResult NewWedding()
        {
            if(ActiveUser == null)
            {
                return RedirectToAction("Register", "Home");
            }

            var myUser = ActiveUser;
            ViewBag.User = myUser;
            return View();
        }

        [HttpPost("create_wedding")]
        public IActionResult CreateWedding(Wedding newWedding)
        {
            // MainUser weddingUser = ActiveUser;

            if(ActiveUser == null)
            {
                return RedirectToAction("Register", "Home");
            }

            if(ModelState.IsValid)
            {
                dbContext.Weddings.Add(newWedding);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.User = ActiveUser;
            return View("NewWedding");
        }

        [HttpGet("rsvp/{weddingID}")]
        public IActionResult AttendWedding(int weddingID)
        {
            Attending attending = new Attending
            {
                UserId = ActiveUser.UserId,
                WeddingId = weddingID
            };
            dbContext.Attendees.Add(attending);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet("unrsvp/{weddingID}")]
        public IActionResult UnattendWedding(int weddingID)
        {
            int? UserId = ActiveUser.UserId;
            int? WeddingId = weddingID;
            Attending unattending = dbContext.Attendees
            .FirstOrDefault(a => a.WeddingId == weddingID && a.UserId == UserId);
            dbContext.Attendees.Remove(unattending);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet("delete/{WeddingID}")]
        public IActionResult DeleteWedding(int WeddingID)
        {
            if(ActiveUser == null)
            {
                return RedirectToAction("Register", "Home");
            }

            Wedding deleteWedding = dbContext.Weddings
            .FirstOrDefault(d => d.WeddingId == WeddingID);
            dbContext.Weddings.Remove(deleteWedding);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Wedding/Index.cshtml
@{
    ViewData["Title"] =  @ViewBag.User.FirstName + "'s Account";
}

<h1>Wecome to Wedding Planner, @ViewBag.User.FirstName!</h1>
<a href="/logout">Logout</a> | <a href="/wedding/new_wedding">Add New Wedding!</a>
<!-- Route to add wedding -->
<hr>
<table class="Wedding-Table">
    <thead>
        <tr>
            <th>Wedding</th>
            <th>Date</th>
            <th>Guest</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Wedding wedding in ViewBag.Weddings)
        {
            <tr>
                <td> 
                    <a href="/wedding/@wedding.WeddingId">@wedding.Bride & @wedding.Groom</a>
                </td>
                <td> @wedding.CreatedAt.ToString("D")</td>
                <td>@wedding.Attendees.Count</td>
                    @{
                        if(@wedding.UserId == ViewBag.User.UserId)
                        {
                            <td>
                                <a href="delete/@wedding.WeddingId">Delete</a>
                            </td>
                        }
                        else if(@wedding.Attendees.
                        Where(att => att.UserId == @ViewBag.User.UserId).FirstOrDefault() == null)
                        {
                            <td>
                                <a href="rsvp/@wedding.WeddingId">Attend</a>
                            </td>
                        }
                        else
                        {
                            <td>
                                <a href="unrsvp/@wedding.WeddingId">Unattend</a>
                            </td>
                        }
                    }
            </tr>
        }
    </tbody>
</table>

Views/Wedding/NewWedding.cshtml
@{
    ViewData["Title"] =  "Add a Wedding!";
}
@model Wedding
<h1>@ViewBag.User.FirstName, let's plan a wedding!</h1>
<a href="/logout">Logout</a> | <a href="/wedding/dashboard">Dashboard</a>

<form asp-action="CreateWedding" asp-controller="Wedding" method="POST">
    <div class="form-group">
        <span asp-validation-for="Bride"></span>
        <label asp-for="Bride">Bride: </label>
        <input class="form-control" asp-for="Bride">
    </div>

    <div class="form-group">
        <span asp-validation-for="Groom"></span>
        <label asp-for="Groom">Groom: </label>
        <input class="form-control" asp-for="Groom">
    </div>

    <div class="form-group">
        <span asp-validation-for="Date"></span>
        <label asp-for="Date">Date: </label>
        <input class="form-control" asp-for="Date">
    </div>

    <div class="form-group">
        <span asp-validation-for="Address"></span>
        <label asp-for="Address">Address: </label>
        <input class="form-control" asp-for="Address">
    </div>
    <div class="form-group">
        <input type="hidden" value="@ViewBag.User.UserId" name="UserId">
    </div>

    <button type="submit">Add Wedding!</button>
</form>

Views/Wedding/WeddingInfo.cshtml
@{
    ViewData["Title"] =  @ViewBag.Wedding.Bride + " & " + @ViewBag.Wedding.Groom + "'s Wedding";
}

<h1>@ViewBag.Wedding.Bride & @ViewBag.Wedding.Groom's Wedding</h1><a href="/logout">Logout</a> | <a href="/wedding/dashboard">Dashboard</a>
<hr>
<h4>Tying The Knot On: @ViewBag.Wedding.Date.ToString("D")</h4>
<h5>Ceremony Address: @ViewBag.Wedding.Address </h5>
<h5>Guests:</h5>
@{
    foreach(Attending attending in ViewBag.Wedding.Attendees)
    {
        <p> - @attending.attendingGuests.FirstName @attending.attendingGuests.LastName</p>
    }
}